name: Build and test on Windows and Linux
on:
  push:
    branches:
      - master
      - develop
      - refactor_client
  pull_request:
    branches:
      - master

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build on Windows
        run: cl test/main.cpp src/simple_cpp_sockets.cpp -Isrc /EHsc /std:c++17
        working-directory: .
      - name: test on Windows
        run: ./main.exe
        working-directory: . 
  build-and-test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Build on Linux
        run: g++ -std=c++17 test/main.cpp -o main -Isrc
        working-directory: .
      - name: test on Linux
        run: ./main
        working-directory: .

