name: Build
on:
  push:
    branches:
      - master
      - non_blocking
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build on Windows
        run: cl main.cpp
        working-directory: ./src

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on Linux
        run: g++ main.cpp -o main
        working-directory: ./src
